spring:
  profiles:
    active: dev
app:
  name: Boot Pigg
  description: ${app.name} is a Spring Boot application
---
spring:
    profiles: dev
server:
    address: 127.0.0.1
logging:
      level:
        root: WARN
        org.springframework.web: INFO
        com.piggsoft: DEBUG
mybatis:
  configLocation: classpath:/MyBatis.xml
  mapperLocations: classpath:/mapper/*.xml
  typeAliasesPackage: com.piggsoft.model
jdbc:
  url: jdbc:mysql://192.168.199.28:3306/boot?useUnicode=true&characterEncoding=utf-8
  username: root
  password: 123456
  driverClassName: com.mysql.jdbc.Driver
---
spring:
    profiles: prod
    datasource:
        url: jdbc:mysql://localhost:3306/test
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
server:
    address: 192.168.1.120